version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    image: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main
    image: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SERVICES_STAT_SERVER_URI=http://stat-server:9090

  ewm-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root